### ISSUE TITLE
Custom Elements as submittable elements

### ISSUE THREAD

**Issue by nektro** [WICG/webcomponents#646] opened 2017-06-28 09:47 UTC
The HTML spec currently defines [submittable elements](https://html.spec.whatwg.org/#category-submit) as the set list of elements that can be used in a form to submit data. That list being `<button>`, `<input>`, `<output>`, `<select>`, and `<textarea>`.

Is there currently any way to make a Custom Element could add itself to this list?

**Comment by annevk** [comment] 2017-06-28 11:53
No, I think this is a duplicate of #187.

**Comment by domenic** [comment] 2017-06-28 13:23
Indeed.

**Closed as completed by domenic** 2017-06-28 13:23 UTC
