### ISSUE TITLE
Slotted content inside a <p>

### ISSUE THREAD

**Issue by pshihn** [WICG/webcomponents#841] opened 2019-09-22 22:29 UTC
Using slotted content in custom-elements is not practical when using inside a `<p>` tag. 

Consider the following:
```html
<p>
  <my-element>
    <div>content</div>
  </my-element>
</p>
```

HTML parser closes the `<p>` tag if it encounters a block element - even though it is inside a custom element (which may already be defined at this point). It doesn't matter if the custom-element is styled as `inline-block` or `block`.

The output is
```html
<p>
  <my-element>
  </my-element>
</p>
<div>content</div>
```

Clearly this will not work. I don't like the idea of not being able to create inline custom-elements inside a paragraph. For example, a custom picture or video element. 

Even if the output was the following, it would have worked for most cases:
```html
<p>
</p>
<my-element>
  <div>content</div>
</my-element>
```

Not an easy thing to solve, especially considering backwards compatibility of the `<p>` tag, but it really sucks for Web Components.

**Comment by annevk** [comment] 2019-09-24 07:23
This is a duplicate of #630 and variants referenced from there. There's no appetite to change the HTML parser so this will unlikely be fixed. At least not within `text/html`.

**Closed as completed by annevk** 2019-09-24 07:23 UTC

**Comment by justinfagnani** [comment] 2019-09-24 14:54
Yes, although this is even a more general user case, IMO.

@pshihn could you add this example to #630?

**Comment by pshihn** [comment] 2019-09-24 15:16
Done.
