### ISSUE TITLE
Expected behaviour of contentEditable, slot and distributed nodes

### ISSUE THREAD

**Issue by bedeoverend** [WICG/webcomponents#579] opened 2016-09-28 23:03 UTC
I'm curious as to what the expected behaviour is in the following situation:

Given this HTML:

``` html
<div id="container">
  Should this be editable?
  <p>Or this?</p>
</div>
```

Where `#container` has a shadow root of:

``` html
<div contenteditable="true">
  <slot></slot>
</div>
```

From what I've read in the spec, contenteditable - when missing - inherits from the "parent element", so should that mean that none of the distributed elements / nodes be editable? Apart from reference to `contenteditable` not propagating down from Shadow Host to its Shadow Trees, I couldn't see any reference in the Shadow DOM spec either.

Trying this out in Chrome 54, the `p` becomes editable, but the unwrapped text node is not - but the contenteditable bounding box still wraps around both when clicking on the text. In Safari 10 neither the `p` element nor text node are editable, however contenteditable still gets focus, and wraps around both, as in Chrome.

What's the expected behaviour here? Apologies if I've missed something.

**Comment by rniwa** [comment] 2016-09-29 00:04
The expected behavior is that nothing inside the slots will become editable.

@hayatoito @domenic @hayatoito

**Comment by hayatoito** [comment] 2016-10-04 07:17
> The expected behavior is that nothing inside the slots will become editable.

Yeah, that is the intended behavior of the current spec.
Let me check whether Blink's implementation is intentional one or not.

**Comment by yosinch** [comment] 2016-10-04 08:35
It seems there are bug in Blink for handling "--webkit-user-modify" CSS property, Blink use "--webkit-user-modify" CSS property to control editability.

BTW, V0 Shadow DOM works as expected.

Sample: https://jsfiddle.net/cx2jgp8t/1/

**Comment by hayatoito** [comment] 2016-10-05 07:31
@yosinch 
Thank you. It sounds that we can close this issue. @yosinch would file a bug for Blink, I expect. :)

**Closed as completed by hayatoito** 2016-10-05 07:31 UTC
Labels: v1, shadow-dom

**Comment by bedeoverend** [comment] 2016-10-05 09:46
Yeah that's cleared it up - thanks everyone! Really appreciate all your work on WC.
