### ISSUE TITLE
2019 TPAC F2F

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#826] opened 2019-07-29 23:59 UTC
Thanks to @LJWatson and @hober, we have a room at TPAC on Tuesday, September 17th.

Minutes are available here: https://www.w3.org/2019/09/17-components-minutes.html

This issue tracks the agenda for this F2F.

## Topics

* ~~ARIA role parity with HTML elements (at 2pm for 30min)~~ discussed on Monday
* Checking in on ::part — any remaining issues to resolve?
* [Custom states](https://github.com/w3c/webcomponents/pull/832/)
* [delegatesFocus](https://github.com/whatwg/html/issues/2013)
* [Scoped custom element registries](https://github.com/w3c/webcomponents/issues/716)
* [Constructible / adopted stylesheets](https://wicg.github.io/construct-stylesheets/)
* Untrusted components
* Stacking UI
* [Default focus behaviors for custom elements](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/custom-element-default-focus.md)
*  Element reference IDL attributes and Shadow DOM
* [Imperative shadow distribution API](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Imperative-Shadow-DOM-Distribution-API.md)
* [Mitigating flash of unstyled content with custom elements](https://docs.google.com/presentation/d/1C3tzhdhB9wIOcJQv-PSzJE9kKhvVNU61Py1fYN2_5z0/edit#slide=id.p)
* JSON modules: They've been [built](https://chromium-review.googlesource.com/c/chromium/src/+/1731108) experimentally in Blink, any plans/concerns from other implementers?
* ~~[CSS modules](https://github.com/w3c/webcomponents/issues/759): discuss open issues, any blockers to adoption of [scoped V1](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md) implementation~~ Ran out of time.
  * ~~Spec draft [here](https://github.com/whatwg/html/pull/4898)~~
 * ~~State propagation of [lang](https://github.com/whatwg/html/issues/4906), [title](https://github.com/whatwg/html/issues/3821) and [dir](https://github.com/whatwg/html/issues/3699)~~ Ran out of time.

**Comment by mfreed7** [comment] 2019-07-30 01:24
I would like to attend this meeting if possible - will signups happen here on this thread, or will this meeting get added to the TPAC registration?

Also, I think you meant Tuesday, Sept 17.

**Comment by rniwa** [comment] 2019-07-30 05:42
Corrected the month.

@LJWatson / @hober : Would there be HTML listing for TPAC? Or should we sign up for WICG?

**Comment by LJWatson** [comment] 2019-08-20 11:52
The ARIA WG would welcome some time to:
* Share progress on HTML role parity in ARIA 1.2
* Discuss plans for ARIA 1.3 and a proposal to prioritise attribute parity

cc ARIA WG co-chairs @jnurthen and @joanmarie

**Comment by annevk** [comment] 2019-08-20 13:11
Is it also possible to have that meeting on another day as it's not directly about web components? (To be clear, it's definitely a meeting worth having.) With regards to web components it might be good to discuss the various APIs around web components and ARIA.

**Comment by LJWatson** [comment] 2019-08-20 13:54
The effort to reach HTML role parity was prompted by Web Components, first raised here in #552, and continued in discussion at [TPAC 2016](https://www.w3.org/2016/09/19-webapps-minutes.html#item03).

**Comment by LJWatson** [comment] 2019-08-20 13:58
If time is limited on Tuesday, perhaps time could be found for it on the ARIA WG agenda on Monday though?

**Comment by jnurthen** [comment] 2019-08-20 14:23
The ARIA working group is fine with either Monday or Tuesday.

**Comment by rniwa** [comment] 2019-08-29 23:01
cc'ing more people for agenda building.

@dandclark @travisleithead @justinfagnani @diervo @caridy @muan @JanMiksovsky @tomalec @tkent-google @rakina

TPAC F2F is usually more focused on resolving issues with existing features and intersections with other WG's specifications; e.g. CSS and accessibility related features. If there are any topics you wish we made more progress, please let us know.

**Comment by jnurthen** [comment] 2019-09-03 17:27
@LJWatson do you have a time for the meeting with ARIA. I am finalising our agenda.
We can do any time except Tuesday morning when we have other joint meetings scheduled.

**Comment by JanMiksovsky** [comment] 2019-09-03 17:27
Topics I’m interested in discussing include:

* Checking in on ::part — any remaining issues to resolve?
* [Custom states](https://github.com/w3c/webcomponents/pull/832/)
* delegatesFocus

Also, could we spend some time discussing support for untrusted components? At the Spring 2019 F2F in Toronto, SalesForce indicated that they do a substantial amount of custom work to defend against security and stability concerns that arise when one org wants to use a component from a different org. It’s my understanding that Amazon has made a large investment in a proprietary component architecture because they don’t want to accept the risks that come with web components. I believe their requirements extend to protecting one internal team from incidental interference caused by components from other internal teams. I recall Apple raising questions about untrusted components back in 2015 or so, but I can’t remember the last time the topic’s been discussed.

**Comment by caridy** [comment] 2019-09-04 03:33
From our side, I will like to see progress on the following items (in order of importance):

* scoped registries (not sure if the we have any progress here, @justinfagnani)
* adopted stylesheets (we need to get on the same page to move this forward)
* delegatesFocus (seems that we are pretty close on this one)
* custom states (hopefully we can get some traction on this one, seems to be small enough)
* aria properties (probably to be discussed on the accessibility forum instead)

Additionally, I will like to see few new avenues to be explored:

* As @JanMiksovsky mentioned, untrusted components is by far the biggest, maybe we can just do a small presentation to highlight the current situation, and see if the group is open for explorations on this topic.
* Stacking (modals, popups, etc, we continue having issues with the limitations imposed by the platform on this regards, maybe Iuri can put something together).

**Comment by LJWatson** [comment] 2019-09-04 07:55
@jnurthen could you find 30 minutes on the ARIA WG schedule on Monday 
perhaps? @annevk @domenic @rniwa, as people involved in the original 
discussion, would that work for you possibly?

**Comment by jnurthen** [comment] 2019-09-04 16:22
> @jnurthen could you find 30 minutes on the ARIA WG schedule on Monday perhaps? @annevk @domenic @rniwa, as people involved in the original discussion, would that work for you possibly?

Monday - 2pm? @LJWatson @annevk @domenic @rniwa

**Comment by rakina** [comment] 2019-09-04 17:49
Recently added the custom element default focusability proposal: https://github.com/w3c/webcomponents/pull/834. Would like to discuss this in TPAC if possible!

**Comment by siusin** [comment] 2019-09-06 15:21
For Remote Participants:

Tuesday, September 17, 2019
8:30 am  |  Japan Time (Tokyo, GMT+09:00)  |  10 hrs

Join WebEx meeting
https://mit.webex.com/mit/j.php?MTID=m4a1eaf3e4e430bb1f37396a2367067f7
Meeting number:	647 038 848
Meeting password:	visit this [member-only archive](https://lists.w3.org/Archives/Member/w3c-archive/2019Sep/0160.html) or ask our co-chairs
Join from a video conferencing system or application
Dial 647038848@mit.webex.com
You can also dial 173.243.2.68 and enter your meeting number.

Join by phone
+1-617-324-0000 US Toll Number
Access code: 647 038 848
Mobile Auto Dial:+1-617-324-0000,,,647038848#

[Add to your calendar](https://mit.webex.com/mit/j.php?MTID=m9cf9fdbb5614bf349fb5e2393089d9fe)

**Comment by rniwa** [comment] 2019-09-10 09:53
I've update the OP with the list of topics suggested so far. Let me know if I missed anything.

**Comment by rakina** [comment] 2019-09-10 09:55
> I've update the OP with the list of topics suggested so far. Let me know if I missed anything.

can you add custom element default focusability: #834?

**Comment by rniwa** [comment] 2019-09-10 09:58
> > I've update the OP with the list of topics suggested so far. Let me know if I missed anything.
> 
> can you add custom element default focusability: #834?

Oops, sorry. Done that.

**Comment by rniwa** [comment] 2019-09-10 10:01
@jnurthen @LJWatson : Monday 2pm ARIA WG time. Is that to discuss how ARIA / AOM interact with the shadow DOM / custom elements?

**Comment by dandclark** [comment] 2019-09-10 19:02
I'm interested in talking about modules, particularly:
* JSON modules: They've been [built](https://chromium-review.googlesource.com/c/chromium/src/+/1731108) experimentally in Blink, any plans/concerns from other implementers?
* [CSS modules](https://github.com/w3c/webcomponents/issues/759): discuss open issues, any blockers to adoption of [scoped V1](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/css-modules-v1-explainer.md) implementation
  * Spec draft [here](https://github.com/whatwg/html/pull/4898)

**Comment by LJWatson** [comment] 2019-09-11 06:32
@rniwa asked:
> : Monday 2pm ARIA WG time. Is that to discuss how ARIA / AOM interact with the shadow DOM / custom elements?>

The original discussion point from @jnurthen was HTML role parity for web components (from #552).

There are different conversations happening around AOM though, including [use cases for immersive web](https://lists.w3.org/Archives/Public/public-apa/2019Sep/0029.html), but I'm not sure how/where/when @alice, @cookiecrook and others are planning discussions.

**Comment by alice** [comment] 2019-09-11 07:52
I would be happy to attend a session to discuss interactions between ARIA/AOM and Shadow DOM/Custom elements. Sounds like it's out of scope for the already scheduled ARIA WG session though.

**Comment by rniwa** [comment] 2019-09-11 09:04
Thanks for the clarifications. So let's schedule 30min ARIA for HTML role parity at 2pm.

@Alice : do you want to discuss AOM in a different time slot? I don't think there is necessarily any blocker / concern in AOM pertaining to Shadow DOM / Custom Elements, is there?

**Comment by alice** [comment] 2019-09-11 12:09
The thing I had in mind to discuss is the interaction between element reference IDL attributes and Shadow DOM boundaries.

**Comment by rniwa** [comment] 2019-09-12 01:35
> The thing I had in mind to discuss is the interaction between element reference IDL attributes and Shadow DOM boundaries.

Alright, I added that as a topic. Any preference on when (as in time) to discuss that on Tuesday (e.g. after ARIA role discussion)?

**Comment by domenic** [comment] 2019-09-12 02:33
I've added two more topics we'd like to discuss if possible:

- [Imperative shadow distribution API](https://github.com/w3c/webcomponents/blob/gh-pages/proposals/Imperative-Shadow-DOM-Distribution-API.md): discussion of what we've learned from the flagged implementation in Chromium, both on the implementation side and based on web developer feedback. Discussion of next steps toward formalizing and incorporating into the spec. @fergal will work on some brief slides to guide the discussion.

- Mitigating flash of unstyled content with custom elements: discussion of the problem of FOUC with custom elements, especially as the world moves away from blocking scripts. We have some tentative sketches of what a solution could look like, but mostly want to open the discussion of the problem space. I will work on some slides.

**Comment by alice** [comment] 2019-09-12 04:11
>  Any preference on when (as in time) to discuss that on Tuesday (e.g. after ARIA role discussion)?

Tuesday is looking pretty free for me so far, other than 11am. I'd like to sit in on the ARIA discussion anyway, so immediately following that would be convenient.

Thank you!

**Comment by rniwa** [comment] 2019-09-12 05:21
@cookiecrook : Does Tuesday 2:30pm also work for you (AOM discussion)?

**Comment by LJWatson** [comment] 2019-09-12 06:43
@rniwa 
>So let's schedule 30min ARIA for HTML role parity at 2pm.>

To confirm, this is on the Tuesday agenda?

**Comment by cookiecrook** [comment] 2019-09-12 08:31
@rniwa Yes

**Comment by smaug----** [comment] 2019-09-12 13:12
State propagation of lang, title and dir (are there other cases?)
https://github.com/whatwg/html/issues/4906
https://github.com/whatwg/html/issues/3821
https://github.com/whatwg/html/issues/3699

In general we should go through the existing issues.

(in addition to those attribute states, we have had some rather tricky issues open for years, selection handling, session history etc.)

**Comment by rniwa** [comment] 2019-09-13 05:32
@smaug---- : Added that as a topic. I agree we should go through existing issues. I think we should probably allocate 2-3 hours of triaging session.

**Comment by rniwa** [comment] 2019-09-15 12:48
@LWatson / @hober : which room do we have on Tuesday & at what time are we starting?

**Comment by tomalec** [comment] 2019-09-15 16:23
Could you also post the IRC channel that will be used for the meeting?

**Comment by smaug----** [comment] 2019-09-15 16:32
I guess we can use the same channel as last time, so, #components on irc.w3.org

**Comment by rniwa** [comment] 2019-09-16 09:04
I talked to Tess in person, and the plan is to meet at 9am at Yoh, 3F.

**Comment by hober** [comment] 2019-09-18 02:29
Thank you, everyone, for a productive and interesting meeting yesterday. The minutes are here: https://www.w3.org/2019/09/17-components-minutes.html

**Comment by annevk** [comment] 2019-09-19 04:24
The next meeting will likely be end of March 2020 in Paris.

**Closed as completed by annevk** 2019-09-19 04:24 UTC
