### ISSUE TITLE
[Custom Elements] Import module

### ISSUE THREAD

**Issue by ParkFramework** [WICG/webcomponents#329] opened 2015-09-25 21:53 UTC
It will be very useful to describe the import attribute in custom element.

Example: `index.html`

``` HTML
<custom-button import="MyClassButton from 'buttons.html'"></custom-button>
```

Example: `buttons.html`

``` HTML
<style>
...
</style>
<script>
export class MyClassButton extends HTMLButtonElement
{
   // Synchronous constructor and other API
}
</script>
```

User agent, automatically loading file and register element.

**Comment by rniwa** [comment] 2015-09-26 07:17
I think more natural way of doing that will be something like:

``` html
<script type="module" src="my-component.js" import="my-button as custom-button">
...
<custom-button>...</custom-button>
<custom-button>...</custom-button>
...
```

**Comment by ParkFramework** [comment] 2015-09-26 23:16
@rniwa Your offer, there is no import CSS styles, file `buttons.html` It contains styles and js script.

**Comment by rniwa** [comment] 2015-09-27 05:44
You can import CSS via `@import` in your custom element's shadow tree.  Since styles are scoped at a shadow boundary, you'd need to include a style element inside your shadow tree anyway.

**Comment by ParkFramework** [comment] 2015-09-27 07:02
Yes, this is to HTML code `buttons.html`, instead of the JS `my-component.js` :)

**Comment by dglazkov** [comment] 2015-09-27 18:38
BTW, there are pretty serious issues with using `@import` in Shadow DOM, uncovered by Polymer folks and diagnosed by @tabaktins/@esprehn. For more details, see: https://lists.w3.org/Archives/Public/www-style/2014Aug/0238.html.

**Comment by dglazkov** [comment] 2015-09-27 18:38
@TabAtkins for realz now.

**Comment by rniwa** [comment] 2015-09-27 20:30
LOL, it's uncanny that I pointed out style sharing as an issue multiple times in the past, and you guys told me `@import` (and cache headers) is the solution.  It was also one of the reasons we wanted to do CSS-based tree scoping.

But now that we're all here, it would be great to tackle this problem.

**Comment by annevk** [comment] 2016-03-11 12:51
This is a duplicate of #136. @dglazkov I recommend filing a distinct issue for `@import` if you had not done so yet.

**Closed as completed by annevk** 2016-03-11 12:51 UTC
Labels: custom-elements
