### ISSUE TITLE
MutationObserver and attachShadow()

### ISSUE THREAD

**Issue by rodneyrehm** [WICG/webcomponents#390] opened 2016-02-22 08:59 UTC
I'm looking for a way to keep track of ShadowRoots being created. Neither does the current implementation of ShadowDOM/MutationObserver in Firefox 44 and Chrome 48 register a mutation for `element.createShadowRoot()` (renamed to `attachShadow()`), nor does either specification mention this situation specifically.

To the best of my knowledge it is currently not possible to get identified when a ShadowRoot is created for an element.

(originally raised at whatwg/dom#170)

**Comment by hayatoito** [comment] 2016-02-29 03:39
Right. There is no way to observe attachShadow().

I'm not sure this is a question or a feature request... Please feel free to reopen if this is a feature request.

**Comment by rodneyrehm** [comment] 2016-02-29 08:19
It is a feature request. But I'm unable to reopen the issue…

**Comment by hayatoito** [comment] 2016-02-29 08:22
Thanks. Let me reopen this.

**Comment by annevk** [comment] 2016-03-09 18:11
This is a duplicate of #204. Sorry for not realizing that earlier. Forgot to search.

**Closed as completed by annevk** 2016-03-09 18:11 UTC
Labels: v2, shadow-dom
