### ISSUE TITLE
Add a non-normative note stating elements in shadow trees aren't exposed as named properties

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#304] opened 2015-09-01 17:02 UTC
I think the following text in the spec

> Window object named properties [HTML] must access the nodes in the document tree.

is meant to clarify that elements in shadow trees aren't exposed as named properties on `Window`.  

Perhaps we want to add an informative note stating that explicitly.

**Comment by annevk** [comment] 2015-09-02 15:37
I don't understand this feedback.

This applies to a huge number of APIs. It wouldn't make sense to enumerate them all. Why this one?

**Comment by rniwa** [comment] 2015-09-02 15:44
That too.  It's a bit strange to explicitly call out this one.  Does DOM spec says only nodes that are in the document (i.e. its root ancestor node is the document) are exposed as named properties?

**Comment by annevk** [comment] 2015-09-02 15:48
It seems pretty clear about "active document": https://html.spec.whatwg.org/multipage/browsers.html#named-access-on-the-window-object

The only curious thing might be whether an `<iframe>` inside a shadow tree creates a nested browsing context or not. And if not, what does it create?

**Comment by rniwa** [comment] 2015-09-04 21:59
It should create a nested browsing context, right? I don't think there is anything special about iframes inside shadow trees.

**Comment by annevk** [comment] 2015-09-05 04:35
Well, if it creates a nested browsing context (and that requires a changed definition of "is in a document" iirc), it would be exposed on `Window`, unless we change that definition somehow.

**Comment by hayatoito** [comment] 2015-09-07 08:00
As the short time fix, we should change `the nodes` to `anything` (or something?) so that it also excludes browsing context in shadow trees?
The intention is "Don't leak anything in shadow trees via `Window`". However, I'm afraid that there is an exception we are missing.

**Comment by annevk** [comment] 2016-02-29 15:41
This is a duplicate of #145 I think.

**Closed as completed** 2016-03-02 05:00 UTC
Labels: shadow-dom, html-dom
