### ISSUE TITLE
CSS scoping for @keyframes in ::slotted(*)

### ISSUE THREAD

**Issue by valdrinkoshi** [WICG/webcomponents#748] opened 2018-03-14 23:10 UTC
I define css keyframe animations into a `shadowRoot`, and want to apply the animation to a distributed element. The `shadowRoot` looks like this:
```html
<style>
  div, ::slotted(*) {
    position: relative;
    left: 0;
    animation-duration: 2s;
    animation-iteration-count: infinite;
    animation-name: move-animation;
  }

  @keyframes move-animation {
    50% { left: 200px; }
  }
</style>

<slot></slot>
<div>moving? (in shadowRoot)</div>
```
I'd expect the `@keyframes` to be applied to elements in the shadowRoot (e.g. the `<div>`) and any distributed element, while keeping the `@keyframes` scoped (aka other elements shouldn't be able to use the same `animation-name`)
Only Safari seems to match this behavior, while in Chrome (stable, canary) and Opera this the distributed elements are not animating. Here the repro http://jsbin.com/raqamon/1/edit?html,output

Is this a browser bug? I couldn't find the behavior described in the [CSS Scoping spec](https://drafts.csswg.org/css-scoping-1/).

**Comment by annevk** [comment] 2018-03-15 07:44
Duplicate of #715 and https://github.com/w3c/csswg-drafts/issues/1995. I also recommend checking the README, we're no longer using this repository to track all Web Components things; a lot has been upstreamed and integrated into the base specifications.

**Closed as completed by annevk** 2018-03-15 07:44 UTC

**Comment by valdrinkoshi** [comment] 2018-03-15 22:13
Oh ok, thanks for the pointer & sorry for the duplicate. 
I did skim through the readme but failed to understand I should have filed in another repo. Maybe a more direct message like `⚠️ file new issues in this repo ⚠️` might help? Or also setting up an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by annevk** [comment] 2018-03-16 07:49
I tried to clarify the README a bit.
