### ISSUE TITLE
Proposal: Add namespace property to ElementRegistrationOptions parameter of Document.registerElement

### ISSUE THREAD

**Issue by hfmanson** [WICG/webcomponents#328] opened 2015-09-24 09:37 UTC
This namespace property is only applicable to XHTML documents and contains the namespace of the new custom element. In the current specification all new custom elements are put in the HTML namespace http://www.w3.org/1999/xhtml.

If the namespace isn't used by the browser for rendering (e.g. http://www.w3.org/1999/xhtml or http://www.w3.org/2000/svg) the dash requirement for new custom element tag names can be removed. This way it is possible to create polyfill XHTML extensions such as XForms, MathML or X3D using custom elements.

I have forked webcomponents.js to demonstrate this enhancement: https://github.com/hfmanson/webcomponentsjs/tree/xml-namespace/ and a live demo can be seen at http://mansoft.nl/webcomponents/xmltests/brb-test-polyfill-ce.xhtml. Look at that page's source code. This projects runs on Firefox (which doesn't natively support document.registerElement). An important restriction on non-HTML custom elements is to no longer use the HTML-specific onclick functions but the generic DOM AddEventListener pattern. The README.md contains further information

The example component 'Big Red Button' is based on a webcomponent sample from Robin Berjon's presentation 'Distributed Extensibility: Finally Done Right?' on XML Prague 2014.

**Comment by travisleithead** [comment] 2015-09-24 18:40
We may need the hyphen to signal other processes as part of the lifecycle of a custom element, for example, to pre-create a constructor for the element. So, I'm not sure that we can remove the hyphen requirement based solely on your rationale above...

**Comment by rniwa** [comment] 2015-09-24 18:54
I'm sure we can add some flag associated with each element name if needed instead.

**Comment by annevk** [comment] 2016-03-11 12:50
This seems like a duplicate of #154. I don't think any browser nor many web developers would be interested in solutions that do not work inside `text/html`, so closing this.

**Closed as completed by annevk** 2016-03-11 12:50 UTC
Labels: custom-elements
