### ISSUE TITLE
Slots in a flat tree

### ISSUE THREAD

**Issue by rniwa** [WICG/webcomponents#308] opened 2015-09-01 20:13 UTC
[Composition Algorithm](https://w3c.github.io/webcomponents/spec/shadow/#composition-algorithm) defined in section 4.1 "unwraps" slots by re-distributing distributed nodes of a distributed slot by invoking [Distributed Nodes Algorithm](https://w3c.github.io/webcomponents/spec/shadow/#dfn-distributed-nodes) in section 3.3.

However, I don't think that should happen.  In the world where re-distribution is explicit, there is no point in stripping out slot elements.  It's better to treat a slot element like any other element and re-distribute it on its entirely.  This will make the distribution/composition algorithm much simpler and allows slot element to be styled properly.

@hober @othermaciej @annevk @travisleithead

**Comment by sorvell** [comment] 2015-09-02 00:38
Where would the distributed nodes be projected?

It would be problematic if they are projected inside the `<slot>`. In that case one couldn't, for example, project elements into an element that has `display: flex`.

```
<x-b>
  SR
    <div style="display: flex;"><slot></slot></div>
  <div>flex item?</div>
```

**Comment by hayatoito** [comment] 2015-09-02 00:55
Thanks for the feedback.

I'd like to treat a slot, as well as an insertion point, _as_ `DocumentFragment`, as ShadowRoot actually is. That has been in my mental model for a long time. By _considering_ both as `DocumentFragment`, everything became clear to me.

I guess someone doesn't like a slot element being left in the document composed tree, given a shadow root is not left in the document composed tree.
IMO, a slot, and an old insertion point as well as a shadow root, should not be on any more than needed to support the distribution and the composition mechanism.

**Comment by rniwa** [comment] 2015-09-02 02:20
> It would be problematic if they are projected inside the `<slot>`. In that case one couldn't, for example, project elements into an element that has `display: flex`.
> 
> ```
>  <x-b>
>   SR
>     <div style="display: flex;"><slot></slot></div>
>   <div>flex item?</div>
> ```

I see.  That's a pretty good argument for keeping the currently spec'ed behavior although it feels like we're working around the limitation of CSS.

If we had a new display type like `display: ignore` which replaces a node with its children for the purpose of box generations, we wouldn't need to do this, right?

One thing I don't like about the current model is the discrepancy between the composed tree as exposed to CSS and the tree event dispatching takes place.  Namely, the event path will include the slot element that is a deep ancestor of the target.

**Comment by rniwa** [comment] 2015-09-02 02:26
> I'd like to treat a slot, as well as an insertion point, _as_ `DocumentFragment`, as ShadowRoot actually is. That has been in my mental model for a long time. By _considering_ both as `DocumentFragment`, everything became clear to me.

I don't understand what you mean by this. A slot element is an element so it certainly can't be a document fragment.

Moreover, as things stand, the concept of "slot" isn't well defined in the spec.  It's a "defined location" according to the spec but there are no definitions of "defined"-ness or what a "location" is.  It could be a (node, offset) pair like a [boundary point](http://www.w3.org/TR/dom/#concept-range-bp) or it could be a node.  Whatever it is, it needs to be precisely defined.  See issues #306 and #307.

**Comment by hayatoito** [comment] 2015-09-02 04:13
Thanks. I think we can close this issue. Please feel free to re-open this if required.
Let me address some comments as separate issues, like #306.

One more note I can add here is that we might want to support the following use case in the future:

``` html
 <table>
  SR
    <slot name="thead"></slot>
    <slot name="tr"></slot>
    ...

  <thead slot="thead">...</thead>
  <tr slot="tr">...</tr>
  <tr slot="tr">...</tr>
  ...
```

In this case, I guess no one is pleasant that `<slot>` would appear between `<table>` and `<thead>` in the composed tree.

**Comment by rniwa** [comment] 2015-09-02 15:02
I don't think we want to do this just for the styling use cases mentioned here.  I think we just need to set [`display: contents`](http://www.w3.org/TR/css-display-3/#box-generation) as the default sheet sheet on slot elements as follows and that should address both use cases mentioned here.

``` css
slot { display: contents; }
```

To put it another way, the composed tree is only useful to CSS box generation and the current distribution algorithm is trying to avoid box generation for slot element manually.  And I'm saying that it's not necessary or desirable since box generation is inherently a CSS concern and should be dealt as such.  

We can preserve the behavior of not generating boxes (so that tables, flex boxes, ec... work) without having to do it manually in the algorithm by simply relying on a CSS feature such as `display: contents` or a new concept in CSS if one is needed.

One huge benefit of this approach is that the author can then override display property, e.g. to show borders around slot elements, if they wanted to, and removes one more magic from shadow DOM.

**Comment by hayatoito** [comment] 2015-09-03 02:03
> One huge benefit of this approach is that the author can then override display property, e.g. to show borders around slot elements, if they wanted to, and removes one more magic from shadow DOM.

FYI, we can get this benefit by wrapping a slot with an arbitrary element, like:

Before:

```
<shadow-host>
  <shadow-root>
    <slot name="xxx">
  <div slot="xxx">...</div>
  <div slot="xxx">...</div>
```

After:

```
<shadow-host>
  <shadow-root>
    <div class="wrapper">
      <slot name="xxx">
  <div slot="xxx">...</div>
  <div slot="xxx">...</div>
```

**Comment by rniwa** [comment] 2015-09-03 03:23
Right, but that's not really my point.  The benefit of making this behavior reliant on CSS is that we'll decouple shadow DOM's distribution algorithm from the matter of box generation so that authors can figure it as they wish.

**Comment by dglazkov** [comment] 2015-09-03 03:47
I think we should try this. We've attempted this before, and failed for a reason I can't remember. I would love to explain `<slot>` as just a UA style that's `slot { display:contents; }`.

**Comment by hayatoito** [comment] 2015-09-03 03:55
I see. I think one good news is this is an implementation detail because users can't see the difference unless users try to style `<slot>` elements, right? Both approaches should have the same result, I think, because we won't expose an API for composed tree traversal.

**Comment by annevk** [comment] 2015-09-03 05:15
Isn't `deepPath` using the composed tree?

**Comment by rniwa** [comment] 2015-09-03 14:01
@annevk : I think `deepPath` would contain the slot elements we distributed nodes through.

@hayatoito : Mostly, yes. One big difference is that using UA stylesheet would mean that the author can override it with some other display type generate boxes on slot elements so it is observable to an extent.

**Comment by rniwa** [comment] 2015-09-17 19:22
Now there are three benefits to take this approach:
1. It reduces the _platform_ magic involved in shadow DOM into smaller primitives that are more familiar to Web developers.
2. The concept of composed tree can be merged with the event path since they would become identical.
3. The semantics of `assignedSlot` and `getDistributedNodes()` become same. That is, `node.assignedNode === slot` if and only if `slot.getDistributedNodes().includes(node)`.

**Comment by dglazkov** [comment] 2015-09-21 15:48
I just remembered one other thing about unwrapping/flattening nodes. In Shadow DOM v0, we had this nice property that the [tree-structural pseudo-classes](https://drafts.csswg.org/selectors-4/#structural-pseudos) operated on the composed tree (example here:https://gist.github.com/dglazkov/e8402f9ab18ad7ef2e7d). I guess the real question is how `display:contents` interacts with tree-structural pseudo-classes?

**Comment by rniwa** [comment] 2015-09-21 16:46
Since `::slotted` can unwrap slots, I don't think this would be an issue.

**Comment by hayatoito** [comment] 2015-09-28 06:53
I'm thinking of adding the following changes to the spec:
- Include slots elements in the composed tree. Issue #308.
- Add fallback contents capability for slots.  Issue #317
- Add a new API, getAssignedNodes(). Issue #322
- Make slots elements be always _slots_. Issue #321.

A blocking issue might be how `::contents` should behave in this new world. I'll file an issue for that.
We'll use a new name, like `::slotted`, for `::contents`.

**Comment by hayatoito** [comment] 2015-09-29 04:47
I forgot to mention that UA should have a UA style, `slot { display: contents}` in the previous comment.
I'm assuming that slots don't generate any boxes by default with this UA style.

I expect that _Layout Tree_ doesn't change at all by default even if we add slots to the document composed tree.

Can I assume that `{display: contents}` is well supported in all UAs?

**Comment by rniwa** [comment] 2015-09-29 04:49
Yeah, if we're making this pseudo element flatten slot elements' assigned node lists, then we should probably refrain from using the term "assigned".  Also, someone pointed out that "assigned" might sound too generic while "slotted" sounds a lot more related to slot elements.

**Comment by hayatoito** [comment] 2015-09-29 05:20
I guess your replied in the wrong place. :)
It looks the reply for 
https://github.com/w3c/webcomponents/issues/331#issuecomment-143935799.

**Comment by dglazkov** [comment] 2015-09-29 14:44
@esprehn pointed out to me that I may know understand all of the implications of using `display: contents` fully. For example, do elements that have that applied still match styles? Should `slot { color: red }` result in assigned elements inheriting red? Will `<slot contenteditable>` do anything? Looking at [the spec](http://www.w3.org/TR/css-display-3/#valdef-display-contents), I am not sure. Adding @TabAtkins, because he probably does.

**Comment by rniwa** [comment] 2015-09-29 19:19
> For example, do elements that have that applied still match styles? Should slot { color: red } result in assigned elements inheriting red?

It should because box generation is separate from style inheritance

> Will `<slot contenteditable>` do anything?

Contenteditable is a DOM concept.  It won't be affected by display types.

**Comment by hayatoito** [comment] 2015-09-30 01:57
> It should because box generation is separate from style inheritance

Hmm. That's not what I expected for `display: contents`. I assumed that `slot {color: red}` does nothing unless users overwrites UA's `slot {display: contents}` with something like `slot {display: block}`.

Let me take another look later.

**Comment by tabatkins** [comment] 2015-09-30 19:31
Elements with `display:contents` are still elements; they still receive styles, participate in inheritance, etc.

All that `display:contents` does is prevent them from generating a box, and "lift" the boxes of their children into their own context (so they can participate in the grandparent's layout, etc.)

> I assumed that `slot {color: red}` does nothing unless users overwrites UA's `slot {display: contents}` with something like `slot {display: block}`.

It "does nothing" _visible, to the slot element itself,_ but the slot element still gets its `color` property set, and that will inherit as normal.  (Tho, unless slots have changed significantly from how `<content>` worked, there's no inheritance from slot->slotted content.)

**Comment by rniwa** [comment] 2015-09-30 20:21
The [section 2.3](https://w3c.github.io/webcomponents/spec/shadow/#composed-trees) in the current shadow DOM says:

> In resolving CSS inheritance, an element must inherit from the parent node in the composed tree, if applicable.

I think this statement needs to be removed/revised since a slot element is the parent node of its assigned nodes in the composed tree.

**Comment by hayatoito** [comment] 2015-10-01 02:30
> > In resolving CSS inheritance, an element must inherit from the parent node in the composed tree, if applicable.
> 
> I think this statement needs to be removed/revised since a slot element is the parent node of its assigned nodes in the composed tree.

We don't need to revise this sentence. Instead, we have to redefine the composition algorithm:
https://w3c.github.io/webcomponents/spec/shadow/#composition-algorithm

The sentence might be unnecessary since I've added the following sentence to the spec recently:

> User agents must use the document composed tree in the visual formatting model, instead of the document tree.

However, explicit might be better than implicit.

Since it turned out that an element with `{display: contents}` should have an effect on style inheritance, I have a concern how we could implement "slots in composed tree" in blink. Let me investigate further.

**Comment by rniwa** [comment] 2015-10-01 02:50
> We don't need to revise this sentence. Instead, we have to redefine the composition algorithm:
> https://w3c.github.io/webcomponents/spec/shadow/#composition-algorithm

We need to revise it because nodes assigned to a slot should inherit its CSS value from its parent in the light DOM (shadow host), not from the parent in the composed tree (slot into which it is assigned).

**Comment by hayatoito** [comment] 2015-10-01 03:01
> We need to revise it because nodes assigned to a slot should inherit its CSS value from its parent in the light DOM (shadow host), not from the parent in the composed tree (slot into which it is assigned).

Could you elaborate it? That sounds like a new proposal which we've never discussed.

**Comment by rniwa** [comment] 2015-10-01 03:17
> > We need to revise it because nodes assigned to a slot should inherit its CSS value from its parent in the light DOM (shadow host), not from the parent in the composed tree (slot into which it is assigned).
> 
> Could you elaborate it? That sounds like a new proposal which we've never discussed.

As far as I can tell, that's what Tab is saying in https://github.com/w3c/webcomponents/issues/308#issuecomment-144515431

**Comment by hayatoito** [comment] 2015-10-01 03:35
I understand what Tab is saying. But I still don't understand what this means clearly:

> nodes assigned to a slot should inherit its CSS value from its parent in the light DOM (shadow host), not from the parent in the composed tree (slot into which it is assigned).

Could you clarify the behavior what you are thinking, using the example of tree of trees in the spec?  https://w3c.github.io/webcomponents/spec/shadow/#composition-example

I appreciate if you would explain from where each node inherits its style in the example.

**Comment by rniwa** [comment] 2015-10-01 03:39
In that example, D and F will inherit style from C even though both of them are slotted into L and appear as child nodes of L in the composed tree (or K if we don't include L, the slot, in the composed tree).

**Comment by hayatoito** [comment] 2015-10-01 03:44
Thank you. I understand what you mean. 

However, such a behavior would be unacceptable because a structure of "style inheritance tree" won't match a structure of "layout tree".

**Comment by rniwa** [comment] 2015-10-01 03:57
Oh, I guess I misunderstood what Tab was saying.  I guess he meant to say the inheritance skips the slot element.

That still raises a question as to whether assigned nodes under a `slot` element should inherit styles from the slot element itself or not.  It would be strange if it didn't given the display value of `slot` elements can be overridden.  e.g. `display: block` was specified on a slot element, then it would be strange to skip it for the purpose of inheritance.

**Comment by tabatkins** [comment] 2015-10-01 17:46
I was speaking on a naive understanding; I could be wrong.  I assumed that inheritance would work over the DOM tree, not the composed tree.  Either is fine from a CSS standpoint.

**Comment by esprehn** [comment] 2015-10-02 07:13
Distributed nodes should inherit from the final destination slot, for example if you have the below example given `<slot name="x" slot="y">`, then the nodes should inherit from `<slot name=y>` if it exists, not from slot x. This is important for a number of use cases, for example if your widget expects a heading element, and will style that with a larger font size. Not doing this also adds a significant amount of complexity since there's a number properties which are internally inherited, for example visibility. Adding visibility: hidden to an ancestor of the final destination slot should hide the contents of it.

I don't think the display value of slot elements should be allowed to be overriden, they're omitted from the composed tree, leaving them in violates a fundamental assumption of our engine:

If Node X has a render object, then the parentNode of X in the composed tree also has a render object.

I know that's at odds with display: contents, but display: contents is theoretical and will be very difficult to implement since it violates this assumption. I don't think it's a v1 feature of the spec for sure.

**Comment by hayatoito** [comment] 2015-10-02 08:00
How about deferring 'including slots in the composed tree' to v2?
`{display: contents}` is not well supported in all UAs and it might require a huge amount of rewriting an engine.

Even if we don't have it in v1, we just lose the ability of styling a distributed node with an inheritance by styling a slot. That sounds a small loss. We can consider adding it later in v2 when `{display: contents}` is well supported.

I'm afraid the worst scenario: We can't ship Shadow DOM v1 soon due to the support cost of `{display: contents}`.

**Comment by rniwa** [comment] 2015-10-02 22:15
I think it's okay for the spec to keep saying slot has `{display: contents;}` and each implementation to fake it for the time being since the compatibility risk is super low.  Given if slot elements were present in the composed tree, slots will get styles from the final destination since inherited values will propagate from the final slot to intermediate slots to each assigned node unless values were specifically overridden.

**Comment by hayatoito** [comment] 2015-10-05 07:17
Okay. Let me lower the priority of this issue. I'll keep this issue open with v2 label, tentatively, so we don't forget to add this to the spec later.

**Comment by rniwa** [comment] 2016-02-12 08:20
Here's one problem I'm encountering with Chrome's `content` element behavior.  When I set `display:none` on `content` element, the nodes distributed to `content` is still shown in the document.  This is extremely counterintuitive.

Since WebKit DOES NOT render the element in this case, we're already non-interoperable in this regard.  I think we probably need to address this matter in v1 after all.

**Comment by hayatoito** [comment] 2016-02-12 08:31
That's an intended behavior in Blink. The document flat tree never includes insertion points nor shadow roots, as the spec says. Blink honors the spec.

**Comment by rniwa** [comment] 2016-02-12 08:34
It doesn't matter whether that's intended or not.  The problem is that it doesn't match the author expectation.

**Comment by hayatoito** [comment] 2016-02-12 08:44
Yeah, I think we all are aware that it is one of the cons.

As a workaround, developers can use `::content` pseudo elements for the purpose.
Now it is available as `::slottted` in v1.

e.g.

``` css
slot::slotted(*) {
  display: none;
}
```

**Comment by rniwa** [comment] 2016-02-12 23:26
Why is that desirable behavior at all?  It seems like it's simply a bug in Blink.

**Comment by hober** [comment] 2016-02-12 23:51
Ideally slot elements should only be as magical as they need to be, and no more magical. I much prefer a world in which they all show up in the composed tree & the UA stylesheet sets display:contents on them to a world in which the engine magically hides them from style resolution.

**Comment by annevk** [comment] 2016-03-11 11:39
Marking this v1 since it seems important to agree on this.

**Comment by hayatoito** [comment] 2016-03-24 04:07
How can we agree on this issue? I would like to move this issue forward.

There are still technical constraints to accept this proposal:
-  Constraint in Blink's engine: https://github.com/w3c/webcomponents/issues/308#issuecomment-144940913
-  No solution for http://github.com/w3c/webcomponents/issues/308#issuecomment-136903096. We do not have any concrete proposal to address this issue.

Given that, I would like to move this issue to v2.
As I explained in https://github.com/w3c/webcomponents/issues/331#issuecomment-185093547, we can support the use case to style distributed nodes in more expressive way than using slots as a hook.

**Comment by rniwa** [comment] 2016-03-24 05:42
> No solution for http://github.com/w3c/webcomponents/issues/308#issuecomment-136903096. We do not have any concrete proposal to address this issue.

The concrete proposal is to use the default style of `display: contents` on every slot element.  This solves the problem of slotted elements being treated is they're direct child nodes of its parent.

**Comment by hayatoito** [comment] 2016-03-24 06:18
Yeah, I know {display: contents} is the hope, however, a lot of HTML elements's definition are not ready for {display: content}, I think.

From https://drafts.csswg.org/css-display-3/#box-generation

>  contents currently only has an effect on box generation and layout. Other things that care about the document tree are unaffected, like counter scopes. Is this what we want?

e.g.

```
<table>
  <div style="display: contents">
      <tr>...</tr>
  </div>
</table>
```

https://html.spec.whatwg.org/#the-tr-element

Most of the definition of HTML elements use _the parent_ directly in their definition and do not take care of the parent element's style. We have to update HTML Standard so that it will find the _effective_ parent, skipping elements with {display: contents}.

And we might have to update the parser too?

Is WebKit ready for this? Unfortunately, Blink is not ready at all for {display: contents}.

**Comment by rniwa** [comment] 2016-03-24 06:46
How else are we going to implement slot elements?  One way or another, browser engines need to support semantics similar to `display: contents`.  We don't need to consider what happens with other elements with `display: contents` since we're talking about slot elements here.

In fact, it's fine for initial implementations of slot elements to not fully respect `display: contents`-ness. For the purpose of writing specifications, however, we should assume `display: contents` exist.  If Blink has issues with `display: contents`, then you should bring that up on www-style instead.

**Comment by hayatoito** [comment] 2016-03-24 06:57
Thanks. I tend to agree, hoping web developers would not complain about Blink about this.
However, before making the final decision, let me consult with other guys.

**Comment by hayatoito** [comment] 2016-03-28 06:24
My biggest concerns are:
1. How can we trust the feature of `{display: contents}`? Can we be 100% sure this will be successful? It looks there is no other spec which bets on its success, AFAIK. Only Shadow DOM looks the early adapter.
2. Suppose that we support "a slot in a flat tree" in the spec, and developers start to style a slot element, that's _un-reversible_ change.
   Later, when we find "{display: contents}" is not a thing, it's too late. We can not change the behavior without breaking the Web site.

Thus, I have to be careful to add a slot in a flat tree. If we support it, that means that Shadow DOM will fail if `{display: contents}` fails.

Is there any significant benefit of adding a slot in a flat tree, which is worth having such a great risk?
Note that we can support "slots in a flat tree" anytime later when we can feel "{display: contents}" is widely accepted.

I am not opposing to "slots in a flat tree", but I am afraid that it's too risky today, and today is not the day.

@tabatkins, WDTY? Do you have a good feeling that "{display: contents}" will become successful??

**Comment by rniwa** [comment] 2016-03-28 06:35
In general, it's a good idea to minimize the number of new "magics" we introduce to the Web.  Being able to describe/de-sugar slot element's behavior in terms of `display: contents` would be "explaining" the platform and "building on top of primitives".  Introducing a shadow-DOM specific CSS box generation mechanism is anti-pattern in this regard (against the Extensible Web Manifest).

**Comment by rniwa** [comment] 2016-03-28 06:38
On more concrete examples, I already hit an interoperability problem with Chrome whereby which it doesn't respect `display: none` on slot elements whereas WebKit did.  Chrome's behavior of ignoring `display:none` was rather surprising for me as an author.  In addition, having to use `:slotted(*)` because styles on slot elements would be ignored has been really annoying.

**Comment by tabatkins** [comment] 2016-03-28 22:10
`display: contents` is useful on the CSS side for a number of things; Shadow DOM is only one of them.

I can't say whether it will succeed or not, as that depends on browser vendors implementing it. That said, I think Firefox has done so.

**Comment by hayatoito** [comment] 2016-03-31 07:27
@tabatkins, thanks.

Can I confirm one more thing? Does the following HTML work as expected (from the view of the spec)?

```
<div style="display: flex;">
  <div style="display: contents;">
    <div>flex item 1</div>
    <div>flex item 2</div>   
    ....
  </div>
</div>
```

This is the raised concern from @sorvell in https://github.com/w3c/webcomponents/issues/308#issuecomment-136903096.

**Comment by tabatkins** [comment] 2016-03-31 16:46
Yes, it works as expected, per spec. I think this works in Firefox right now if you want to test it.

**Comment by hayatoito** [comment] 2016-03-31 23:01
@tabatkins , thanks. I appreciate that.

Then, it looks reasonable to support "add slots in a flat tree" with UA-style "slot { display:contents; }" in the spec. I'll update the spec.

Since Blink has not supported "display: contents" yet and its engine requires a huge rewrite to support "a slots in a flat tree", Blink's initial implementation of v1 will not fully respect it.

If someone has a concern about this decision, please let us know that.

**Comment by esprehn** [comment] 2016-04-01 01:22
Looking at WebKit I think right now slotted elements inherit from the parent of the `<slot>`, and webkit only respects display: none. That is doing `slot { display: block; }` has no effect. 

I'm very hesitant to ship with matching behavior, it doesn't seem like that's how display: contents was supposed to work. display: contents also has implications, for example are counter increments considered when declared on the slot? What about quoting level? Does slot::before and slot::after work? does display: contents disable ::before? (I hope so).  What about slot::first-line ?

I'd like to work out the details before we commit to making display: contents be a thing, and slot having a dependency on that technology. The current system is easy to explain, <slot> is just gone by the time styles are computed. There's no subtle rules for what does and does not apply.

**Comment by tabatkins** [comment] 2016-04-01 16:12
> Looking at WebKit I think right now slotted elements inherit from the parent of the <slot>, and webkit only respects display: none. That is doing slot { display: block; } has no effect.
> 
> I'm very hesitant to ship with matching behavior, it doesn't seem like that's how display: contents was supposed to work.

Correct, that is a broken implementation.  Firefox has, afaik, a _real_ implementation of display:contents.

> display: contents also has implications, for example are counter increments considered when declared on the slot? What about quoting level? Does slot::before and slot::after work? does display: contents disable ::before? (I hope so). What about slot::first-line ?

All defined by https://drafts.csswg.org/css-display/#valdef-display-contents.

Counters work on the element tree; they're not disturbed by box-tree manipulation.  (If they were, then the 'order' property would mess with them too.)  Quotes aren't very specific (they're defined by language lingering from CSS2, when we were _much_ less explicit about the element/box/fragment divisions), but they _should_ work the same.  Pseudo-elements still generate as normal.

**Comment by rniwa** [comment] 2016-04-05 19:10
Telecom agreement: We'd spec this as `display: contents`. While there are unknowns with respect to its behavior, and there is disagreements within Google regarding this feature, it seems okay to use this given WebKit and Gecko are implementing this feature in near future.

**Closed as completed** 2016-04-07 08:29 UTC
Labels: v1, shadow-dom, html-dom
