### ISSUE TITLE
[IDEA] deferred upgrade for Custom Elements.

### ISSUE THREAD

**Issue by trusktr** [WICG/webcomponents#559] opened 2016-08-29 20:24 UTC
I'm not sure if upgrade is async in the new spec, but in v0 in Chrome it appears not to be (at least that is my guess based on the hacks I've described in #558.

Here I propose that Custom Element class registration should not cause immediate upgrade, and should wait for the next turn, at which point the engine can _upgrade elements in depth-first order_ with some guarantee that all the necessary classes have already been registered.

I believe that this would prevent me from requiring the hacks described in #558.

**Comment by trusktr** [comment] 2016-08-29 20:32
Does the issue make sense? Let me know if I need to explain it differently. Essentially, **_I never have any problem if my elements don't have to be upgraded**_ (i.e. the classes are registered before the elements are ever created). The problems arise when the elements are created before the classes are registered, in which case they need to be upgraded and that means **_causes some of my library code to execute before all the classes have been registered and therefore the code can fail because the custom element classes are minimally coupled and depend on things existing on all the elements, where those things are defined in multiple custom element classes**_.

**Comment by trusktr** [comment] 2016-08-29 20:59
Here's the problem explained as simply as I can, and with possibly incorrect assumptions as I'm not completely familiar with Chrome's v0 implementation:

Suppose I wish to register two element classes, `SomeElement` and `OtherElement`. Then, suppose the pre-existing markup exists:

``` html
<some-el>
  <other-el>
  </other-el>
</some-el>
```

Then, the following JS is executed:

``` js
document.registerElement('some-el', SomeElement)
document.registerElement('other-el', OtherElement)
```

In an attempt to describe the problem I see from observing Chrome's v0 behavior, it seems that the first call to `document.registerElement('some-el', SomeElement)` causes `some-el` elements to be upgraded and their `attachedCallback` methods to be fired before the registration of `OtherElement`, so the children of the `some-el` will not be of the correct type when `attachedCallback` is called. By deferring logic with the `setTimeout` hack shown in #558, I can run logic _after_ the children have also been upgraded to be of type `OtherElement` (_after_ the execution of `document.registerElement('other-el', OtherElement)`).

I don't have a simple reproduction, but will post back if I do.

**Comment by rniwa** [comment] 2016-08-29 21:00
We've visited this idea before and the problem is that we'll delay the painting of a custom element during parsing until all of its children are parsed, which is not acceptable.

**Comment by trusktr** [comment] 2016-08-29 21:13
@rniwa Although I run `document.registerElement` calls in the `<head>` of the `<html>` document and while the body contains

``` html
<some-el>
  <other-el>
  </other-el>
</some-el>
```

then when the `attachedCallback` on `some-el` is called, it will be able to see the non-yet-upgraded child `other-el`, which leads me to believe that when `attachedCallback` of `some-el` is fired that the tree has already been parsed, otherwise how can the children of `some-el` be visible inside it's `attachedCallback`? It also seems that the upgrades happen in pre-order, so `some-el` is upgraded and it's `attachedCallback` fired, then `other-el` is upgraded and it's `attachedCallback` fired.

However, if the elements are attached into DOM _after_ the class registrations, then the `attachedCallbacks` will fire in post-order, in which case everything works fine without hacks.

So, it seems there just needs to be some type of mechanism that can guarantee that `attachedCallbacks` are always fired in post-order (depth-first), and it seems that for this to happen that  the upgrades should be delayed until all classes are registered.

But, I'm not even sure why if I run my `document.registerElement` calls in the `<head>` why the upgrades happen in pre-order. Is this because of the parsing, as in

```
<some-el> <-- when the parser reaches here, it upgrades `some-el`?
  <other-el> <-- then when it reaches here it *first* calls attachedCallback on some-el, *then* upgrades other-el?
  </other-el>
</some-el>
```

**Comment by domenic** [comment] 2016-08-29 21:15
I would really urge you to stop making assumptions based on old implementations, and actually read the spec. There are so many unfounded assumptions here in these (very long) posts, that I don't have time to walk you through where they are wrong.

**Comment by trusktr** [comment] 2016-08-29 23:00
@domenic I will strive to do that.

Here is simple reproduction of the problem on jsfiddle (tested in Chrome): https://jsfiddle.net/dgbqdL33 (look at console output).

In `TEST CASE 1`, how would we wait for the child elements to be upgraded when the logic in the parent will depend on the child being `instanceof` the upgraded type?  In `TEST CASE 2`, it works fine because the elements are added to DOM _after_ the class registration.

Is this fixed in v1?

**Comment by domenic** [comment] 2016-08-29 23:01
I'd suggest you trying it in Chrome Canary with v1 syntax and so on. Or read the spec.

**Comment by trusktr** [comment] 2016-08-29 23:18
@domenic The same problem persists using v1 API in Chrome Canary (see console output): https://jsfiddle.net/wkwmzLwL.

This is problematic because a parent element may need to have branching logic depending on which type of custom-element children are detected. f.e.

``` js
class SomeElement extends HTMLElement {
    connectedCallback() {
        for (let child of this.children)
            if (child instanceof SomeElement)
                // ...
            else if (child instanceof OtherElement)
                // ...
            else if (child instanceof AnotherElement)
                // ...
    }
}
```

This can be solved using a timeout hack, so the code would become

``` js
class SomeElement extends HTMLElement {
    connectedCallback() {
        setTimeout(() => {
            for (let child of this.children)
                if (child instanceof SomeElement)
                    // ...
                else if (child instanceof OtherElement)
                    // ...
                else if (child instanceof AnotherElement)
                    // ...
        }, 0)
    }
}
```

Here's a fiddle that shows that the hack works (see output): https://jsfiddle.net/aqp4uaja

**Comment by rniwa** [comment] 2016-08-29 23:28
I think this problem also goes away if we [add back `childrenChangedCallback`](https://github.com/w3c/webcomponents/issues/550).

**Comment by rniwa** [comment] 2016-08-29 23:32
For now, you can work around it by notifying parent element from a child element's `connectedCallback` and `disconnectedCallback`.

**Comment by trusktr** [comment] 2016-08-30 06:26
@rniwa 

> I think this problem also goes away if we [add back `childrenChangedCallback`](https://github.com/w3c/webcomponents/issues/550).

True, if that callback would be fired when an element is upgraded, at which point we can run an `instanceof` check successfully.

> For now, you can work around it by notifying parent element from a child element's connectedCallback and disconnectedCallback.

But as I mentioned earlier, that (child-to-parent notification/observation) doesn't work with distribution into closed shadow trees, which is why I've changed my API to be parent-to-child which should always work, just that I've had to do some hacks like with `setTimeout` above. Even with a closed tree, a parent can look into a `<slot>` and notify children, but it doesn't work the other way around, so I've settled with only parent-to-child notification/observation.

**Comment by rniwa** [comment] 2016-08-31 07:03
Perhaps what we need is an event that fires when a node gets assigned to some slot?  Sort of the counterpart of `slotchange` event which fires on the assigned node instead of the slot to which the node was assigned.

**Comment by trusktr** [comment] 2016-08-31 23:34
@rniwa I think that would be handy! That is similar to the idea I had with [`slottedCallback`](https://github.com/w3c/webcomponents/issues/527). Maybe having both would be optimal, because `slottedCallback` can only be taken advantage of with Custom Elements, while something like a `slotted` event can be observed on any element without having to write a custom element.

**Comment by trusktr** [comment] 2016-08-31 23:58
@rniwa 

> I think this problem also goes away if we [add back `childrenChangedCallback`](https://github.com/w3c/webcomponents/issues/550).

Which criteria would cause a `childrenChangedCallback` to fire? f.e. when a child is connected, disconnected, upgraded. Anything else? An attribute change could be considered a change. Maybe it is better to make specific callbacks for specific changes. f.e. `childUpgradedCallback`, `childConnectedCallback`, `childDisconnectedCallback`, `childAttributeChangedCallback`, etc.

**Comment by annevk** [comment] 2018-02-17 12:42
@trusktr if you still think you need such events, could you explain them clearly in a new issue? This one is rather convoluted and hard to digest. Thanks.

**Closed as completed by annevk** 2018-02-17 12:42 UTC
Labels: custom-elements

**Comment by trusktr** [comment] 2018-02-18 02:24
@annevk Sure, made a new issue here: https://github.com/w3c/webcomponents/issues/737
