### ISSUE TITLE
Web Components and Form Submit Fields

### ISSUE THREAD

**Issue by StokeMasterJack** [WICG/webcomponents#529] opened 2016-06-29 17:54 UTC
The web component spec should provide a way to expose form submit fields similar to the way you currently are allowed to expose properties. Thus a web component's API would consists of 4 things:
- Methods
- Properties
- Events
- Form Submit Fields

This was a web component can play nicely inside of an html form. I made a blog post that more clearly spells out the problem:

http://dave-ford.blogspot.com/2016/06/web-components-and-form-submit-fields.html

**Comment by domenic** [comment] 2016-06-29 18:00
Dupe of https://github.com/w3c/webcomponents/issues/187, I believe.

**Closed as completed by domenic** 2016-06-29 18:00 UTC

**Comment by StokeMasterJack** [comment] 2016-06-29 18:04
Thanks

On Wed, Jun 29, 2016 at 11:00 AM, Domenic Denicola <notifications@github.com
