### ISSUE TITLE
CE reaction queue's not-really-sync behavior doesn't provide strong enough guarantees about when reactions occur

### ISSUE THREAD

**Issue by bicknellr** [WICG/webcomponents#616] opened 2016-12-10 01:30 UTC
The custom elements reaction queue is difficult to reason about because nested queue flushing can cause callbacks to be run even when the information those callbacks are meant to convey is no longer valid.

[This gist](https://gist.github.com/bicknellr/567661eff48bb130add3bb1be86e37e2) shows a situation with two elements, one the parent of the other, where the parent sets an attribute on the child during its `connectedCallback` but the child removes that same attribute during its `connectedCallback`. The inner element's `attributeChangedCallback` is called with incorrect values because a pending `connectedCallback` reaction in the queue causes calls to functions with `[CEReactions]` to be 'delayed' until subsequent. [This gist](https://gist.github.com/bicknellr/a964b91fcbae51df5361085b5fd666e2) is the same as the last but has lots of extra logging. Here's the output:

```
 1 CALL fragment = document.importNode(template.content, true)
 2 EXIT fragment = document.importNode(template.content, true)
 3 CALL document.body.appendChild(fragment)
 4 | START <x-outer> connectedCallback
 5 | <x-outer>.children[0].getAttribute('a'): null
 6 | CALL <x-outer>.children[0].setAttribute('a', 'foo')
 7 | | START <x-inner> connectedCallback
 8 | | <x-inner>.getAttribute('a'): foo
 9 | | CALL <x-inner>.removeAttribute('a')
10 | | | START <x-inner> attributeChangedCallback ( name: a , old: null , new: foo )
11 | | | <x-inner>.getAttribute('a'): null
12 | | | END <x-inner> attributeChangedCallback
13 | | | START <x-inner> attributeChangedCallback ( name: a , old: foo , new: null )
14 | | | <x-inner>.getAttribute('a'): null
15 | | `-END <x-inner> attributeChangedCallback
16 | | EXIT <x-inner>.removeAttribute('a')
17 | | <x-inner>.getAttribute('a'): null
18 | `-END <x-inner> connectedCallback
19 | EXIT <x-outer>.children[0].setAttribute('a', 'foo')
20 | <x-outer>.children[0].getAttribute('a'): null
21 `-END <x-outer> connectedCallback
22 EXIT document.body.appendChild(fragment)
```

The most obviously confusing (ha) thing going on here is what happens starting from the parent's call to `setAttribute` of the child (L6 above). When this call is made, an `attributeChangedCallback` reaction is enqueued but the child's queue already contains a pending `connectedCallback` reaction and causes that reaction to be called first. Then, as mentioned earlier, the child removes the attribute `a` from itself during its `connectedCallback`. However, when the child calls `removeAttribute` (L9; has `[CEReactions]`), the `attributeChangedCallback` reaction setting `a` to `'foo'` that was added shallower in the stack is already in the queue and is called next (L10). So, the child's `attributeChangedCallback` ends up being called with arguments `['a', null, 'foo']` even though `this.getAttribute('a')` inside that callback returns `null` because the last thing to actually happen to attribute `a` was that it was removed!

What this means is code running in `attributeChangedCallback` can't assume that the values provided to it are in any way representative the state of that element when the callback is called. If we continue assuming the specced behavior to be 'correct', for the moment, then custom elements' `setAttribute` inherently becomes an asynchronous operation. A response to this might be, "No, the `attributeChangedCallback` for any given `setAttribute` or `removeAttribute` call will occur synchronously before that call has completed.", and this would be correct.

However, the real problem arises when implementing `attributeChangedCallback`. If `attributeChangedCallback` isn't guaranteed to be called synchronously, then, to avoid doing incorrect work in response to a callback that may have already been invalidated, the element must wait. Additionally, there is no way to know how long to wait: waiting until `this.getAttribute(name) === newValue` isn't necessarily sufficient because there may be other attribute changes pending (or soon to be triggered) that eventually cycle `name`'s value back to `newValue` but occur after something that would change how the element responds to `name`'s value becoming `newValue`. This means the earliest safe time for the element to act is after there are no more frames of author JS on the stack, which can only be best approximated with a microtask. So, because the element can't safely act synchronously *because* can't know that its state has stabilized until at least the next microtask, `setAttribute` has effectively become async.

IMHO, this makes working with custom elements' attributes unusably cumbersome because every custom element must now supply some asynchronous signal to indicate that the element has finished acting in response to a given call to `setAttribute` or `removeAttribute`. Also, every user of a custom element must know and use these async signals whenever changing attributes of a custom element or initially interacting with a custom element, if that element was created by the parser. I feel confident saying that these signals will differ between custom element authors and even amongst the same author's elements.

**This problem is not limited to `attributeChangedCallback`.** [This gist](https://gist.github.com/bicknellr/2f5e1c0bda51f4c63579aa771d75af72) shows a very similar situation where `connectedCallback` of an element is called when the element is disconnected.

I think the justification for having the custom elements reactions queue rather than making these actions synchronous needs to be reconsidered. Even with a large number of elements to be assembled, is natively testing a boolean when building the tree ("Is this a custom element?") really that expensive? And, as far as potentially exposing intermediate state goes, it seems like this problem is actually a *result* of the queue. For example, if I wanted to build this tree:
```html
<x-outer a="1">
  <x-inner b="2"></x-inner>
</x-inner>
```
I could do this:
```javascript
var outer = document.createElement('x-outer');
outer.setAttribute('a', '1');

var inner = document.createElement('x-inner');
inner.setAttribute('b', '2');
outer.appendChild(inner);

document.body.appendChild(outer);
```
... and the callbacks would be called in a sane order and the state of the tree also makes sense: `inner` would have already responded to `b` changing to `'2'` before it is appended to the tree, when `outer` might potentially call `inner.setAttribute('b', somethingElse)`. Why should cloning a template be any different?

**Comment by bicknellr** [comment] 2016-12-10 01:31
cc @domenic; this is what I brought up earlier today.

**Comment by sorvell** [comment] 2016-12-10 02:06
In the example above, the most unexpected behavior is that the user of `<x-outer>.children[0]` called `setAttribute('a', 'foo')` but from her perspective saw a result of `getAttribute('a') ==  null`.

It seems that this behavior could be addressed by changing the spec at https://html.spec.whatwg.org/#custom-element-reactions such that the `[CEReactions]` steps were modified via the bold text below:

1. Before executing the algorithm's steps: **Pop the element queue from the custom element reactions stack, and invoke custom element reactions in that queue.** Push a new element queue onto the custom element reactions stack.
1. After executing the algorithm's steps: Pop the element queue from the custom element reactions stack, and invoke custom element reactions in that queue.

It seems like this would replay the reactions in a more expected order and would not result in the unexpected behavior described above.

**Comment by rniwa** [comment] 2016-12-10 03:01
That doesn’t quite work. We’re already in the middle of invoking custom element reactions in the element queue (which contains both `x-outer` and `x-inner`) we had pop’ed inside `appendChild`.  There is no element queue to pop in the stack.

**Comment by domenic** [comment] 2016-12-12 22:50
Right, now that I see the proposed solution written out, it does indeed not work great. The push/pop pairs go together; we can't introduce a third pop, as that will make things unbalanced.

I'm not sure what a better solution would be, though :-/. If someone has one, it'd be great to investigate.

The spec notes the constraints here:

> Additionally, the precise ordering of these reactions is managed via a somewhat-complicated stack-of-queues system, described below. The intention behind this system is to guarantee that custom element reactions always are invoked in the same order as their triggering actions, at least within the local context of a single custom element. (Because custom element reaction code can perform its own mutations, it is not possible to give a global ordering guarantee across multiple elements.)

That is, it's specifically not guaranteed that ordering *between* elements is preserved; it's only within a single element. I believe this came from an analysis by @dominiccooney explaining that it was impossible to satisfy both constraints at once. I can't find that document now though.

It does seem like if your goal is to get the current state of the attribute, instead of a log of what happened to it, actually using getAttribute is best. The arguments tell you that at some point in time the attribute changed, but the attribute could have changed multiple times; you don't know if you're in the first attributeChangedCallback or the second. All you know is that ordering will be preserved.

**Comment by rniwa** [comment] 2016-12-13 02:27
Yeah, in a way, you’re hitting the fundamental limitation of custom element lifecycle callback timing. Unless callbacks are fully synchronous, it’s always possible for a callback to called with an outdated value, or some elements to be in an out-dated state.

In general, mutating another element inside a custom element callback should be considered an anti-pattern and should be avoided because of this problem. Making such a mutation can lead to very fragile racy components that steps on each other’s toes as many apps that use mutation events have demonstrated in the past 10+ years.

**Comment by dominiccooney** [comment] 2016-12-20 05:34
I'm sympathetic to the difficulty of using custom element callbacks efficiently and effectively.

Ironically the solution here may be *more* callbacks, like "this element's queue was exhausted." I haven't thought through this in detail though. It would need care to make it efficient and useful. It might make sense to wait and see if custom elements authors are using requestAnimationFrame or polling state a lot to do similar things in less efficient ways.

> Unless callbacks are fully synchronous,

By the way, even "fully synchronous" callbacks are insufficient, because one DOM operation (for example, remove) can change the state of multiple custom elements at once. You have to call the disconnected callbacks in some order, so the observed state of the other element is out of sync (ahead) of its callbacks.

**Comment by rniwa** [comment] 2016-12-20 05:48
> > Unless callbacks are fully synchronous,
>
> By the way, even "fully synchronous" callbacks are insufficient, because one DOM operation (for example, remove) can change the state of multiple custom elements at once.

Well, by fully synchronous, I meant that each DOM operation would be calling JS as it mutates DOM.  Each DOM operation can really be broken into pieces in terms of pre-insert, and other primitive operations in the DOM specification.  e.g. removing all children would result in each child getting a callback as itself is getting removed and so on. 

This, however, is precisely what Google objected as one issue they can’t live with so I don’t think we can do this.

**Comment by dominiccooney** [comment] 2016-12-20 06:04
> This, however, is precisely what Google objected as one issue they can’t live with so I don’t think we can do this.

This characterization is accurate. We believe the script running on callstacks and in states we're not set up to handle isn't manageable, based on our experience with MutationEvents.

**Comment by annevk** [comment] 2017-09-06 07:50
Closing based on the last couple of comments.

**Closed as completed by annevk** 2017-09-06 07:50 UTC
Labels: custom-elements
