### ISSUE TITLE
CustomElementRegistry per shadow DOM

### ISSUE THREAD

**Issue by falsandtru** [WICG/webcomponents#792] opened 2019-02-09 10:45 UTC
I think custom elements should be able to be defined per shadow DOM like css.

```js
window.customElements.define('my-custom-element', MyCustomElement0);
shadowroot1.customElements.define('my-custom-element', MyCustomElement1);
shadowroot2.customElements.define('my-custom-element', MyCustomElement2);
```

**Comment by annevk** [comment] 2019-02-10 12:51
That's not shadow DOM, but anyway, duplicate of #716.

**Closed as completed by annevk** 2019-02-10 12:51 UTC

**Comment by falsandtru** [comment] 2019-02-10 12:55
Thanks for your navigation.
